version: '3'
services:
  myapp:
    build:
      context: ./server # Replace with the path to your application code
      dockerfile: Dockerfile # Replace with the actual name of your Dockerfile
    restart: on-failure # Restart the container automatically if it stops
    expose:
      - "5000"

  # nginx:
  #   build:
  #     context: ./nginx # Replace with the path to your application code
  #     dockerfile: nginx.Dockerfile # Replace with the actual name of your Dockerfile
  #   ports:
  #     - "80:80"
  #   restart: always # Restart the container automatically if it stops

  waf:
      build: waf-3
      ports:
          - "80:80"